server:
  port: 9099
spring:
  application:
    name: oss-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
minio:
  # API 端点
  endpoint: "http://192.168.1.100:9000"
  # API 端点(CDN)
  endpoint-cdn: "https://oss.simple.com/"
  # 默认 Bucket 存储桶名称
  bucketName: public
  # Access Key
  access-key: fmQleb8YBFUeMyxxxxxx
  # Secret Key
  secret-key: Bz6z1LVSW1vie4si3zxmtZVq666MV0v1MWxxxxxx
# swagger 配置
springdoc:
  api-docs:
    # true - 开启API文档功能，false - 关闭API文档功能
    enabled: true
  swagger-ui:
    enabled: true
    # “list”（仅展开标记）、“full”（展开标记和操作）、“none”（不展开任何内容）。
    docExpansion: none
    # “alpha”（按路径字母数字排序），“method”（按HTTP方法排序）
    operationsSorter: method
  # GET请求下，让swagger将DTO封装入参解析成form参数
  default-flat-param-object: true